# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85f59b7c3e68f909fda04c7ba9e2d0391cf66a3647b8c3ba9b09fc034763a9d062dfd39c057cfa5102aaa554fa2d0385f4da0a0179baf74e556f0c5c335a5248

test:
  secret_key_base: 267cc6582d8674e2e5837fe12b9e8005aa2ede817af72c9a6175ec531a9af97a8b06e0b43cdb0209a4b2f1aae60dbba1317c6f5e18846049daa6abff0fe0cf73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
